// Centralized Hebrew strings file
// All user-facing text should be defined here

export const strings = {
  common: {
    loading: "טוען...",
    save: "שמור",
    saving: "שומר...",
    cancel: "ביטול",
    delete: "מחק",
    edit: "ערוך",
    close: "סגור",
    back: "חזרה",
    yes: "כן",
    no: "לא",
    all: "הכל",
    unknown: "לא ידוע",
    error: "שגיאה",
    noResults: "לא נמצאו תוצאות",
    id: "מזהה",
    actions: "פעולות",
    history: "היסטוריה",
    percent: "%",
  },

  app: {
    title: "ניהול תיוגים",
  },

  auth: {
    login: "התחבר",
    loggingIn: "מתחבר...",
    loginTitle: "מערכת ניהול תיוגים",
    loginSubtitle: "התחבר למערכת כדי להמשיך",
    loginError: "שגיאה בהתחברות",
    register: "הרשם",
    registering: "נרשם...",
    registerTitle: "הרשמה למערכת",
    registerSubtitle: "צור חשבון חדש",
    registerError: "שגיאה בהרשמה",
    registerSuccess: "נרשמת בהצלחה!",
    registerWelcome: "ברוך הבא למערכת",
    noAccount: "אין לך חשבון?",
    hasAccount: "יש לך חשבון?",
    registerHere: "הרשם כאן",
    loginHere: "התחבר כאן",
    email: "אימייל",
    password: "סיסמא",
    username: "שם משתמש",
    usernamePlaceholder: "שם משתמש ייחודי",
    displayName: "שם תצוגה",
    displayNamePlaceholder: "השם שיוצג במערכת",
    fillAllFields: "יש למלא את כל השדות",
    logout: "התנתק",
  },

  tags: {
    title: "תיוגים",
    recordsShown: "רשומות מוצגות",
    exportExcel: "ייצוא לאקסל",
    addQuestion: "הוסף שאלה חדשה",
    noTags: "לא נמצאו תיוגים",
    deleted: "התיוג נמחק",
    question: "שאלה",
    answerType: "סוג תשובה",
    answerValue: "ערך תשובה",
    draft: "טיוטה",
    lastEditor: "עורך אחרון",
    updated: "עודכן",
    created: "נוצר",
    versions: "גרסאות",
    cubes: "קוביות",
    freeText: "טקסט חופשי",
  },

  tagEditor: {
    createTitle: "יצירת תיוג חדש",
    editTitle: "עריכת תיוג",
    questionLabel: "שאלה *",
    questionPlaceholder: "הזן את השאלה...",
    answerTypeLabel: "סוג תשובה *",
    addCube: "הוסף קובייה",
    selectCube: "בחר קובייה...",
    totalWeight: "סה״כ משקל:",
    distributeEvenly: "חלוקה שווה",
    topX: "TOP X",
    weightThreshold: "סף משקל כולל (%)",
    freeTextLabel: "תוכן התשובה *",
    freeTextPlaceholder: "הזן את תוכן התשובה...",
    saveAsDraft: "שמור כטיוטה",
    savedSuccess: "נשמר בהצלחה!",
    saveError: "שגיאה בשמירה",
    validationQuestion: "יש להזין שאלה",
    validationCubes: "יש להוסיף לפחות קובייה אחת",
    validationWeights: (total: string) => `סכום המשקלים חייב להיות 100% (כרגע ${total}%)`,
    validationTopX: "TOP X חייב להיות לפחות 1",
    validationFreeText: "יש להזין תוכן תשובה",
  },

  deleteDialog: {
    title: "מחיקת תיוג",
    description: "האם אתה בטוח שברצונך למחוק תיוג זה? פעולה זו לא ניתנת לביטול.",
  },

  filters: {
    searchByQuestion: "חיפוש לפי שאלה...",
    searchByAnswer: "חיפוש לפי תשובה (טקסט חופשי)...",
    filters: "פילטרים",
    clearAll: "נקה הכל",
    cubeName: "שם קובייה",
    user: "משתמש",
    fromDate: "מתאריך",
    selectDate: "בחר תאריך",
  },

  pagination: {
    rowsPerPage: "שורות בעמוד:",
    of: "מתוך",
    page: "עמוד",
  },

  versionHistory: {
    title: "היסטוריית גרסאות",
    versionsCount: "גרסאות",
    selectToCompare: "בחר 2 גרסאות להשוואה",
    compareVersions: "השוואת גרסאות",
    backToList: "חזור לרשימה",
    current: "נוכחית",
    compare: "השווה",
    selected: "נבחר",
    differences: "הבדלים:",
    noDifferences: "אין הבדלים",
    questionField: "שאלה",
    answerTypeField: "סוג תשובה",
    cubesField: "קוביות",
    freeTextContentField: "תוכן טקסט",
    draftStatusField: "סטטוס טיוטה",
    topXField: "TOP X",
    weightThresholdField: "סף משקל",
    questionLabel: "שאלה:",
    answerTypeLabel: "סוג תשובה:",
    cubesLabel: "קוביות:",
    contentLabel: "תוכן:",
    draftLabel: "טיוטה:",
    changedFieldsLabel: "שדות ששונו:",
    versionFrom: "גרסה מ-",
  },

  settings: {
    title: "הגדרות",
    backToTags: "חזרה לתיוגים",
    profileTitle: "פרופיל",
    profileDescription: "עדכן את פרטי הפרופיל שלך",
    displayNameLabel: "שם תצוגה",
    profilePicture: "תמונת פרופיל",
    uploadImage: "העלה תמונה",
    uploadError: "שגיאה בהעלאה",
    saveChanges: "שמור שינויים",
    profileUpdated: "הפרופיל עודכן בהצלחה!",
    fontSizeTitle: "גודל גופן",
    fontSizeSmall: "קטן",
    fontSizeMedium: "בינוני",
    fontSizeLarge: "גדול",
    fontSizeXlarge: "גדול מאוד",
    changePasswordTitle: "שינוי סיסמא",
    currentPassword: "סיסמא נוכחית",
    newPassword: "סיסמא חדשה",
    changePassword: "שנה סיסמא",
    passwordChanged: "הסיסמא שונתה בהצלחה!",
    passwordMinLength: "הסיסמא החדשה חייבת להכיל לפחות 6 תווים",
  },

  theme: {
    lightMode: "מצב בהיר",
    darkMode: "מצב כהה",
  },

  export: {
    id: "מזהה",
    question: "שאלה",
    answerType: "סוג תשובה",
    answerValue: "ערך תשובה",
    draft: "טיוטה",
    lastEditor: "עורך אחרון",
    updatedAt: "עודכן בתאריך",
    createdAt: "נוצר בתאריך",
    versions: "גרסאות",
    sheetName: "תיוגים",
  },

  notFound: {
    title: "404",
    message: "הדף לא נמצא",
    backHome: "חזרה לדף הבית",
  },
} as const;
